export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español (Spanish)' },
  { code: 'fr', name: 'Français (French)' },
  { code: 'de', name: 'Deutsch (German)' },
  { code: 'it', name: 'Italiano (Italian)' },
  { code: 'pt', name: 'Português (Portuguese)' },
  { code: 'nl', name: 'Nederlands (Dutch)' },
  { code: 'ru', name: 'Русский (Russian)' },
  { code: 'zh_cn', name: '简体中文 (Chinese Simplified)' },
  { code: 'zh_tw', name: '繁體中文 (Chinese Traditional)' },
  { code: 'ja', name: '日本語 (Japanese)' },
  { code: 'ko', name: '한국어 (Korean)' },
  { code: 'ar', name: 'العربية (Arabic)' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'ur', name: 'اردو (Urdu)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'tr', name: 'Türkçe (Turkish)' },
  { code: 'vi', name: 'Tiếng Việt (Vietnamese)' },
  { code: 'fa', name: 'فارسی (Persian)' },
  { code: 'pl', name: 'Polski (Polish)' },
  { code: 'uk', name: 'Українська (Ukrainian)' },
  { code: 'ro', name: 'Română (Romanian)' },
  { code: 'el', name: 'Ελληνικά (Greek)' },
  { code: 'cs', name: 'Čeština (Czech)' },
  { code: 'sv', name: 'Svenska (Swedish)' },
  { code: 'no', name: 'Norsk (Norwegian)' },
  { code: 'da', name: 'Dansk (Danish)' },
  { code: 'fi', name: 'Suomi (Finnish)' },
  { code: 'he', name: 'עברית (Hebrew)' },
  { code: 'id', name: 'Bahasa Indonesia (Indonesian)' },
  { code: 'ms', name: 'Bahasa Melayu (Malay)' },
  { code: 'th', name: 'ภาษาไทย (Thai)' },
  { code: 'tl', name: 'Tagalog (Filipino)' },
  { code: 'hu', name: 'Magyar (Hungarian)' },
  { code: 'hr', name: 'Hrvatski (Croatian)' },
  { code: 'sk', name: 'Slovenčina (Slovak)' }
];
