export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español (Spanish)' },
  { code: 'fr', name: 'Français (French)' },
  { code: 'de', name: 'Deutsch (German)' },
  { code: 'it', name: 'Italiano (Italian)' },
  { code: 'pt', name: 'Português (Portuguese)' },
  { code: 'nl', name: 'Nederlands (Dutch)' },
  { code: 'ru', name: 'Русский (Russian)' },
  { code: 'zh_cn', name: '简体中文 (Chinese Simplified)' },
  { code: 'zh_tw', name: '繁體中文 (Chinese Traditional)' },
  { code: 'ja', name: '日本語 (Japanese)' },
  { code: 'ko', name: '한국어 (Korean)' },
  { code: 'ar', name: 'العربية (Arabic)' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'ur', name: 'اردو (Urdu)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'tr', name: 'Türkçe (Turkish)' },
  { code: 'vi', name: 'Tiếng Việt (Vietnamese)' },
  { code: 'fa', name: 'فارسی (Persian)' },
  { code: 'pl', name: 'Polski (Polish)' },
  { code: 'uk', name: 'Українська (Ukrainian)' },
  { code: 'ro', name: 'Română (Romanian)' },
  { code: 'el', name: 'Ελληνικά (Greek)' },
  { code: 'cs', name: 'Čeština (Czech)' },
  { code: 'sv', name: 'Svenska (Swedish)' },
  { code: 'no', name: 'Norsk (Norwegian)' },
  { code: 'da', name: 'Dansk (Danish)' },
  { code: 'fi', name: 'Suomi (Finnish)' },
  { code: 'he', name: 'עברית (Hebrew)' },
  { code: 'id', name: 'Bahasa Indonesia (Indonesian)' },
  { code: 'ms', name: 'Bahasa Melayu (Malay)' },
  { code: 'th', name: 'ภาษาไทย (Thai)' },
  { code: 'tl', name: 'Tagalog (Filipino)' },
  { code: 'hu', name: 'Magyar (Hungarian)' },
  { code: 'hr', name: 'Hrvatski (Croatian)' },
  { code: 'sk', name: 'Slovenčina (Slovak)' }
];

export const TRANSLATIONS = {
  en: {
    basic: "Basic Mode",
    scientific: "Scientific",
    fraction: "Fraction",
    percentage: "Percentage",
    timer: "Timers / Clock",
    history: "History",
    clearHistory: "Clear History",
    emptyHistory: "No calculations yet",
    clearInputs: "Clear Inputs",
    sound: "Sound Tones",
    fullscreen: "Fullscreen",
    about: "About OmniCalc",
    result: "Result",
    stepByStep: "Step-by-Step",
    keyboard: "Keyboard Guide",
    language: "Language",
    simpleLayout: "Simple Layout",
    trigFunctions: "Trigo & Functions",
    stepSolver: "Step-by-Step Solver",
    financialRates: "Financial Rates",
    lapsAlarm: "Laps & Alarm Chime",
    precisionTrig: "Precision Trigonometry Engine",
    clientSafe: "Client-Side Safe Environment",
    quickChange: "From / to change",
    theme: "Theme",
    improFraction: "Mixed Number",
    rawRatio: "RAW RATIO",
    reducedAnswer: "REDUCED ANSWER"
  },
  es: {
    basic: "Modo Básico",
    scientific: "Científico",
    fraction: "Fracción",
    percentage: "Porcentaje",
    timer: "Temporizadores / Reloj",
    history: "Historial",
    clearHistory: "Borrar Historial",
    emptyHistory: "Aún no hay cálculos",
    clearInputs: "Limpiar Entradas",
    sound: "Sonoridad",
    fullscreen: "Pantalla Completa",
    about: "Sobre OmniCalc",
    result: "Resultado",
    stepByStep: "Paso a Paso",
    keyboard: "Guía de Teclado",
    language: "Idioma",
    simpleLayout: "Diseño Simple",
    trigFunctions: "Trigonométricas",
    stepSolver: "Solucionador Paso a Paso",
    financialRates: "Tasas Financieras",
    lapsAlarm: "Vueltas y Alarma",
    precisionTrig: "Motor de Trigonometría de Precisión",
    clientSafe: "Entorno del Cliente Seguro",
    quickChange: "Cambio de De/A",
    theme: "Tema",
    improFraction: "Número Mixto",
    rawRatio: "PROPORCIÓN BRUTA",
    reducedAnswer: "RESPUESTA REDUCIDA"
  },
  fr: {
    basic: "Mode Basique",
    scientific: "Scientifique",
    fraction: "Fraction",
    percentage: "Pourcentage",
    timer: "Minuteurs / Horloge",
    history: "Historique",
    clearHistory: "Effacer l'historique",
    emptyHistory: "Aucun calcul pour le moment",
    clearInputs: "Effacer les Entrées",
    sound: "Tonalités Clics",
    fullscreen: "Plein écran",
    about: "À propos d'OmniCalc",
    result: "Résultat",
    stepByStep: "Étape par Étape",
    keyboard: "Guide du Clavier",
    language: "Langue",
    simpleLayout: "Mise en page simple",
    trigFunctions: "Trigonométrie & Fonctions",
    stepSolver: "Résolveur étape par étape",
    financialRates: "Taux Financiers",
    lapsAlarm: "Tours & Alarme",
    precisionTrig: "Moteur de trigonométrie de précision",
    clientSafe: "Environnement client sécurisé",
    quickChange: "De / à variation",
    theme: "Thème",
    improFraction: "Nombre mixte",
    rawRatio: "FRACTION BRUTE",
    reducedAnswer: "RÉPONSE RÉDUITE"
  },
  de: {
    basic: "Basismodus",
    scientific: "Wissenschaftlich",
    fraction: "Bruchrechnen",
    percentage: "Prozent",
    timer: "Timer / Uhr",
    history: "Verlauf",
    clearHistory: "Verlauf löschen",
    emptyHistory: "Noch keine Berechnungen",
    clearInputs: "Eingaben löschen",
    sound: "Tonsignale",
    fullscreen: "Vollbild",
    about: "Über OmniCalc",
    result: "Ergebnis",
    stepByStep: "Schritt-für-Schritt",
    keyboard: "Tastaturanleitung",
    language: "Sprache",
    simpleLayout: "Einfaches Layout",
    trigFunctions: "Trigonometrie",
    stepSolver: "Bruchschrittlöser",
    financialRates: "Finanzsätze",
    lapsAlarm: "Runden & Alarmton",
    precisionTrig: "Präzisions-Trigonometrie-Engine",
    clientSafe: "Sichere Client-Anwendung",
    quickChange: "% Änderung von/zu",
    theme: "Design",
    improFraction: "Gemischte Zahl",
    rawRatio: "ROHES VERHÄLTNIS",
    reducedAnswer: "GEKÜRZTE ANTWORT"
  },
  it: {
    basic: "Modo Base",
    scientific: "Scientifico",
    fraction: "Frazioni",
    percentage: "Percentuale",
    timer: "Timer / Orologio",
    history: "Cronologia",
    clearHistory: "Cancella Cronologia",
    emptyHistory: "Nessun calcolo registrato",
    clearInputs: "Cancella Input",
    sound: "Suoni Tasti",
    fullscreen: "Schermo Intero",
    about: "Informazioni su OmniCalc",
    result: "Risultato",
    stepByStep: "Passo dopo Passo",
    keyboard: "Guida Tastiera",
    language: "Lingua",
    simpleLayout: "Layout Semplice",
    trigFunctions: "Trigonometria e Funzioni",
    stepSolver: "Risolutore Frazioni",
    financialRates: "Tassi Finanziari",
    lapsAlarm: "Giri e Allarme",
    precisionTrig: "Motore Trigonometrico di Precisione",
    clientSafe: "Ambiente Client Sicuro",
    quickChange: "Variazione da/a",
    theme: "Tema",
    improFraction: "Numero Misto",
    rawRatio: "RAPPORTO GREZZO",
    reducedAnswer: "RISPOSTA RIDOTTA"
  },
  pt: {
    basic: "Modo Básico",
    scientific: "Científico",
    fraction: "Fração",
    percentage: "Porcentagem",
    timer: "Temporizadores / Relógio",
    history: "Histórico",
    clearHistory: "Limpar Histórico",
    emptyHistory: "Nenhum cálculo ainda",
    clearInputs: "Limpar Entradas",
    sound: "Efeitos Sonoros",
    fullscreen: "Tela Cheia",
    about: "Sobre o OmniCalc",
    result: "Resultado",
    stepByStep: "Passo a Passo",
    keyboard: "Guia do Teclado",
    language: "Idioma",
    simpleLayout: "Layout Simples",
    trigFunctions: "Trigonométricas",
    stepSolver: "Solucionador de Frações",
    financialRates: "Taxas Financeiras",
    lapsAlarm: "Voltas e Alarme",
    precisionTrig: "Motor de Trigonometria de Precisão",
    clientSafe: "Ambiente Seguro no Cliente",
    quickChange: "Variação de / para",
    theme: "Tema",
    improFraction: "Número Misto",
    rawRatio: "FRAÇÃO BRUTA",
    reducedAnswer: "RESPOSTA REDUZIDA"
  },
  nl: {
    basic: "Basis modus",
    scientific: "Wetenschappelijk",
    fraction: "Breuken",
    percentage: "Percentage",
    timer: "Timers / Klok",
    history: "Geschiedenis",
    clearHistory: "Geschiedenis Wissen",
    emptyHistory: "Nog geen berekeningen",
    clearInputs: "Invoer Wissen",
    sound: "Geluidseffecten",
    fullscreen: "Volledig Scherm",
    about: "Over OmniCalc",
    result: "Resultaat",
    stepByStep: "Stap-voor-stap",
    keyboard: "Toetsenbord Gids",
    language: "Taal",
    simpleLayout: "Eenvoudige Layout",
    trigFunctions: "Trigonometrie",
    stepSolver: "Stapsgewijze Oplosser",
    financialRates: "Financiële Tarieven",
    lapsAlarm: "Ronden & Alarm",
    precisionTrig: "Precisie Trigonometrie Motor",
    clientSafe: "Client-Side Veilige Omgeving",
    quickChange: "Wijziging van/naar",
    theme: "Thema",
    improFraction: "Gemengd Getal",
    rawRatio: "RUWE VERHOUDING",
    reducedAnswer: "GEREGUSTEERD ANTWOORD"
  },
  ru: {
    basic: "Базовый режим",
    scientific: "Научный",
    fraction: "Дроби",
    percentage: "Проценты",
    timer: "Таймеры / Часы",
    history: "История",
    clearHistory: "Очистить историю",
    emptyHistory: "Нет вычислений",
    clearInputs: "Очистить ввод",
    sound: "Звук клавиш",
    fullscreen: "Полный экран",
    about: "О приложении OmniCalc",
    result: "Результат",
    stepByStep: "Шаг за шагом",
    keyboard: "Клавиатура",
    language: "Язык",
    simpleLayout: " Простой макет",
    trigFunctions: "Тригонометрия",
    stepSolver: "Пошаговое решение",
    financialRates: "Финансовые ставки",
    lapsAlarm: "Круги и будильник",
    precisionTrig: "Точный тригонометрический движок",
    clientSafe: "Безопасная клиентская среда",
    quickChange: "Изменение от/до",
    theme: "Тема",
    improFraction: "Смешанное число",
    rawRatio: "НЕОБРАБОТАННАЯ ДРОБЬ",
    reducedAnswer: "СОКРАЩЕННЫЙ ОТВЕТ"
  },
  zh_cn: {
    basic: "基本模式",
    scientific: "科学计算",
    fraction: "分数计算",
    percentage: "百分比",
    timer: "计时器 / 时钟",
    history: "计算历史",
    clearHistory: "清空历史",
    emptyHistory: "暂无计算记录",
    clearInputs: "清空输入",
    sound: "按键音效",
    fullscreen: "全屏模式",
    about: "关于 OmniCalc",
    result: "计算结果",
    stepByStep: "分步解析",
    keyboard: "键盘快捷键",
    language: "语言选择",
    simpleLayout: "精简界面",
    trigFunctions: "三角函数与公式",
    stepSolver: "分步求解器",
    financialRates: "财务利率",
    lapsAlarm: "分圈与闹铃",
    precisionTrig: "高精度三角函数引擎",
    clientSafe: "安全纯客户端环境",
    quickChange: "百分比变化幅度",
    theme: "主题配色",
    improFraction: "带分数",
    rawRatio: "原始比例",
    reducedAnswer: "最简结果"
  },
  zh_tw: {
    basic: "基本模式",
    scientific: "科學計算",
    fraction: "分數計算",
    percentage: "百分比",
    timer: "計時器 / 時鐘",
    history: "計算歷史",
    clearHistory: "清除歷史",
    emptyHistory: "暫無計算記錄",
    clearInputs: "清除輸入",
    sound: "按鍵音效",
    fullscreen: "全螢幕模式",
    about: "關於 OmniCalc",
    result: "計算結果",
    stepByStep: "分步解析",
    keyboard: "鍵盤快捷鍵",
    language: "語言選擇",
    simpleLayout: "精簡介面",
    trigFunctions: "三角函數與公式",
    stepSolver: "分數分步求解器",
    financialRates: "財務利率",
    lapsAlarm: "計圈與鬧鈴",
    precisionTrig: "高精度三角函數引擎",
    clientSafe: "安全純用戶端環境",
    quickChange: "百分比變化幅度",
    theme: "主題配色",
    improFraction: "帶分數",
    rawRatio: "原始比例",
    reducedAnswer: "最簡結果"
  },
  ja: {
    basic: "基本モード",
    scientific: "関数電卓",
    fraction: "分数計算",
    percentage: "パーセント",
    timer: "タイマー / 時計",
    history: "履歴",
    clearHistory: "履歴をクリア",
    emptyHistory: "計算履歴はありません",
    clearInputs: "入力をクリア",
    sound: "キータッチ音",
    fullscreen: "全画面表示",
    about: "OmniCalcについて",
    result: "計算結果",
    stepByStep: "計算プロセスの表示",
    keyboard: "キーボード設定",
    language: "言語",
    simpleLayout: "標準レイアウト",
    trigFunctions: "三角関数と対数",
    stepSolver: "分数展開ソルバー",
    financialRates: "パーセント変化率",
    lapsAlarm: "ラップとアラーム音",
    precisionTrig: "高精度三角関数エンジン",
    clientSafe: "安全なクライアントサイド環境",
    quickChange: "値の増減変化率",
    theme: "テーマ",
    improFraction: "帯分数",
    rawRatio: "元の比率",
    reducedAnswer: "約分結果"
  },
  ko: {
    basic: "기본 모드",
    scientific: "공학용",
    fraction: "분수 계산",
    percentage: "백분율",
    timer: "타이머 / 시계",
    history: "기록",
    clearHistory: "기록 지우기",
    emptyHistory: "계산 기록이 없습니다",
    clearInputs: "입력 지우기",
    sound: "버튼 소리",
    fullscreen: "전체 화면",
    about: "OmniCalc 정보",
    result: "결과",
    stepByStep: "단계별 풀이",
    keyboard: "키보드 단축키 안내",
    language: "언어 선택",
    simpleLayout: "심플 레이아웃",
    trigFunctions: "삼각함수 & 공식",
    stepSolver: "단계별 해결사",
    financialRates: "백분율 비율 계산",
    lapsAlarm: "랩 타임 및 알람",
    precisionTrig: "정밀 삼각법 엔진",
    clientSafe: "안전한 클라이언트측 환경",
    quickChange: "값의 증가/감소 계산",
    theme: "테마",
    improFraction: "대분수",
    rawRatio: "약분 전 비율",
    reducedAnswer: "약분 후 답"
  },
  ar: {
    basic: "الوضع الأساسي",
    scientific: "علمي",
    fraction: "كسور",
    percentage: "نسبة مئوية",
    timer: "مؤقت / ساعة",
    history: "السجل",
    clearHistory: "مسح السجل",
    emptyHistory: "لا توجد عمليات بعد",
    clearInputs: "مسح المدخلات",
    sound: "صوت الأزرار",
    fullscreen: "ملء الشاشة",
    about: "حول OmniCalc",
    result: "النتيجة",
    stepByStep: "خطوة بخطوة",
    keyboard: "دليل الكيبورد",
    language: "اللغة",
    simpleLayout: "تنسيق بسيط",
    trigFunctions: "المثلثات والدوال",
    stepSolver: "حل الكسور بالتفصيل",
    financialRates: "المعدلات المالية",
    lapsAlarm: "الجولات والمنبه",
    precisionTrig: "محرك حساب المثلثات الدقيق",
    clientSafe: "بيئة آمنة على مستوى العميل",
    quickChange: "التغير من / إلى",
    theme: "المظهر",
    improFraction: "عدد كسري مختلط",
    rawRatio: "النسبة الخام",
    reducedAnswer: "الكسر المبسط"
  },
  hi: {
    basic: "साधारण मोड",
    scientific: "वैज्ञानिक गणना",
    fraction: "भिन्न गणना",
    percentage: "प्रतिशत",
    timer: "टाइमर / घड़ी",
    history: "इतिहास",
    clearHistory: "इतिहास मिटाएं",
    emptyHistory: "कोई गणना इतिहास नहीं",
    clearInputs: "इनपुट साफ करें",
    sound: "कुंजी ध्वनि",
    fullscreen: "पूर्ण स्क्रीन",
    about: "OmniCalc परिचय",
    result: "परिणाम",
    stepByStep: "चरण-दर-चरण",
    keyboard: "कीबोर्ड गाइड",
    language: "भाषा चुनें",
    simpleLayout: "सरल ढांचा",
    trigFunctions: "त्रिकोणमिति और कार्य",
    stepSolver: "भिन्न चरण हलकर्ता",
    financialRates: "वित्तीय प्रतिशत",
    lapsAlarm: "लैप और अलार्म टोन",
    precisionTrig: "सटीक त्रिकोणमिति इंजन",
    clientSafe: "सुरक्षित क्लाइंट-साइड पर्यावरण",
    quickChange: "प्रतिशत वृद्धि / गिरावट",
    theme: "थीम",
    improFraction: "मिश्रित भिन्न",
    rawRatio: "मूल अनुपात",
    reducedAnswer: "सरलीकृत उत्तर"
  },
  bn: {
    basic: "সাধারণ মোড",
    scientific: "বৈজ্ঞানিক",
    fraction: "ভগ্নাংশ",
    percentage: "শতাংশ",
    timer: "টাইমার / ঘড়ি",
    history: "ইতিহাস",
    clearHistory: "ইতিহাস মুছুন",
    emptyHistory: "এখনো কোনো গণনা নেই",
    clearInputs: "ইনপুট সাফ করুন",
    sound: "ক্লিক শব্দ",
    fullscreen: "ফুল স্ক্রিন",
    about: "OmniCalc সম্পর্কে",
    result: "ফলাফল",
    stepByStep: "ধাপে ধাপে সমাধান",
    keyboard: "কীবোর্ড গাইড",
    language: "ভাষা",
    simpleLayout: "সহজ বিন্যাস",
    trigFunctions: "ত্রিকোণমিতি ও ফাংশন",
    stepSolver: "ধাপে ধাপে ভগ্নাংশ সমাধান",
    financialRates: "আর্থিক শতকরা হার",
    lapsAlarm: "ল্যাপ ও অ্যালার্ম সাইরেন",
    precisionTrig: "নির্ভুল ত্রিকোণমিতি ইঞ্জিন",
    clientSafe: "নিরাপদ ক্লায়েন্ট-সাইড পরিবেশ",
    quickChange: "বৃদ্ধি/হ্রাস পরিবর্তন",
    theme: "থিম",
    improFraction: "মিশ্র ভগ্নাংশ",
    rawRatio: "মূল ভগ্নাংশ অনুপাত",
    reducedAnswer: "লঘুকৃত উত্তর ভগ্নাংশ"
  },
  pa: {
    basic: "ਸਧਾਰਨ ਮੋਡ",
    scientific: "ਵਿਗਿਆਨਕ",
    fraction: "ਭਿੰਨ ਅੰਕ",
    percentage: "ਪ੍ਰਤੀਸ਼ਤ",
    timer: "ਟਾਈਮਰ / ਘੜੀ",
    history: "ਇਤਿਹਾਸ",
    clearHistory: "ਇਤਿਹਾਸ ਸਾਫ਼ ਕਰੋ",
    emptyHistory: "ਕੋਈ ਇਤਿਹਾਸ ਨਹੀਂ",
    clearInputs: "ਇਨਪੁਟ ਸਾਫ਼ ਕਰੋ",
    sound: "ਬਟਨ ਦੀ ਆਵਾਜ਼",
    fullscreen: "ਪੂਰੀ ਸਕ੍ਰੀਨ",
    about: "OmniCalc ਬਾਰੇ",
    result: "ਨਤੀਜਾ",
    stepByStep: "ਕਦਮ-ਦਰ-ਕਦਮ",
    keyboard: "ਕੀਬੋਰਡ ਗਾਈਡ",
    language: "ਭਾਸ਼ਾ",
    simpleLayout: "ਸਧਾਰਨ ਖਾਕਾ",
    trigFunctions: "ਤ੍ਰਿਕੋਣਮਿਤੀ",
    stepSolver: "ਭਿੰਨ ਹੱਲਕਾਰ",
    financialRates: "ਵਿੱਤੀ ਦਰਾਂ",
    lapsAlarm: "ਲੈਪਸ ਅਤੇ ਅਲਾਰਮ",
    precisionTrig: "ਸਟੀਕ ਤ੍ਰਿਕੋਣਮਿਤੀ ਇੰਜਣ",
    clientSafe: "ਸੁਰੱਖਿਅਤ ਸਥਾਨਕ ਵਾਤਾਵਰਣ",
    quickChange: "ਤਬਦੀਲੀ ਦਾ ਪ੍ਰਤੀਸ਼ਤ",
    theme: "ਥੀਮ",
    improFraction: "ਮਿਸ਼ਰਤ ਭਿੰਨ",
    rawRatio: "ਅਣ-ਸੋਧਿਆ ਅਨੁਪਾਤ",
    reducedAnswer: "ਸੋਧਿਆ ਉੱਤਰ"
  },
  ur: {
    basic: "سادہ موڈ",
    scientific: "سائنسی حساب",
    fraction: "کسر",
    percentage: "فیصد",
    timer: "ٹائمر / گھڑی",
    history: "سائنس کی تاریخ",
    clearHistory: "تاریخ صاف کریں",
    emptyHistory: "ابھی تک کوئی حساب نہیں ہے",
    clearInputs: "ان پٹ مٹائیں",
    sound: "بٹنز کی کلک آواز",
    fullscreen: "فل اسکرین",
    about: "ایپ کے بارے میں",
    result: "نتیجہ",
    stepByStep: "مرحلہ وار حل",
    keyboard: "کی بورڈ گائیڈ",
    language: "زبان",
    simpleLayout: "سادہ ڈیزائن",
    trigFunctions: "مثلثیاتی دالہ جات",
    stepSolver: "مرحلہ وار کسر کے حل",
    financialRates: "مالیاتی شرح فیصد",
    lapsAlarm: "لیپ ٹائم اور الارم چائم",
    precisionTrig: "انتہائی درست مثلثیاتی انجن",
    clientSafe: "محفوظ ترین کلائنٹ ماحول",
    quickChange: "فیصدی تبدیلی سے/تک",
    theme: "تھیم",
    improFraction: "مخلوط کسر",
    rawRatio: "بنیادی کسر نسبت",
    reducedAnswer: "مختصر کسر جواب"
  },
  te: {
    basic: "సాధారణ మోడ్",
    scientific: "సైంటిఫిక్",
    fraction: "భిన్నాలు",
    percentage: "శాతం",
    timer: "టైమర్ / గడియారం",
    history: "చరిత్ర",
    clearHistory: "చరిత్ర తుడిచివేయి",
    emptyHistory: "ఇంకా ఎలాంటి లెక్కలు లేవు",
    clearInputs: "ఇన్‌పుట్‌లు క్లియర్ చేయి",
    sound: "కీప్యాడ్ సౌండ్",
    fullscreen: "పూర్తి స్క్రీన్",
    about: "OmniCalc గురించి",
    result: "ఫలితం",
    stepByStep: "స్టెప్-బై-స్టెప్",
    keyboard: "కీబోర్డ్ గైడ్",
    language: "భాష",
    simpleLayout: "సాధారణ లేఅవుట్",
    trigFunctions: "త్రికోణమితి",
    stepSolver: "భిన్నాల స్టెప్ సాల్వర్",
    financialRates: "ఆర్థిక లెక్కల శాతం",
    lapsAlarm: "ల్యాప్స్ & అలారం చైమ్",
    precisionTrig: "ఖచ్చితమైన త్రికోణమితి ఇంజిన్",
    clientSafe: "సురక్షిత క్లయింట్ వాతావరణం",
    quickChange: "శాతంలో మార్పు",
    theme: "థీమ్",
    improFraction: "మిశ్రమ భిన్నం",
    rawRatio: "ముడి భిన్నం",
    reducedAnswer: "అత్యంత సరళమైన రూపం"
  },
  mr: {
    basic: "साधा मोड",
    scientific: "वैज्ञानिक गणना",
    fraction: "अपूर्णांक",
    percentage: "टक्केवारी",
    timer: "टाईमर / घड्याळ",
    history: "इतिहास",
    clearHistory: "इतिहास पुसा",
    emptyHistory: "अजून कोणतीही गणना नाही",
    clearInputs: "साफ करा",
    sound: "बटण आवाज",
    fullscreen: "पूर्ण स्क्रीन",
    about: "OmniCalc बद्दल",
    result: "निकाल",
    stepByStep: "टप्प्याटप्प्याने",
    keyboard: "कीबोर्ड मार्गदर्शक",
    language: "भाषा",
    simpleLayout: "सोपी मांडणी",
    trigFunctions: "त्रिकोणमिती आणि कार्य",
    stepSolver: "अपूर्णांक स्टेप सॉल्वर",
    financialRates: "आर्थिक टक्केवारी",
    lapsAlarm: "लॅप्स आणि अलार्म टोन",
    precisionTrig: "निश्चित त्रिकोणमिती इंजिन",
    clientSafe: "सुरक्षित स्थानिक वातावरण",
    quickChange: "वाढ / घट टक्केवारी",
    theme: "थीम",
    improFraction: "मिश्र अपूर्णांक",
    rawRatio: "मूळ अपूर्णांक गुणोत्तर",
    reducedAnswer: "संक्षिप्त उत्तर"
  },
  ta: {
    basic: "சாதாரண பயன்முறை",
    scientific: "அறிவியல்",
    fraction: "பின்னங்கள்",
    percentage: "சதவீதம்",
    timer: "டைமர் / கடிகாரம்",
    history: "வரலாறு",
    clearHistory: "வரலாற்றை அழி",
    emptyHistory: "இன்னும் கணக்கீடுகள் இல்லை",
    clearInputs: "உள்ளீடுகளை அழி",
    sound: "பொத்தான் விசை ஒலி",
    fullscreen: "முழுத்திரை",
    about: "OmniCalc பற்றி",
    result: "முடிவு",
    stepByStep: "படி-படியாக",
    keyboard: "விசைப்பலகை வழிகாட்டி",
    language: "மொழி",
    simpleLayout: "எளிய தளவமைப்பு",
    trigFunctions: "முக்கோணவியல்",
    stepSolver: "பின்னங்களின் படி தீர்வு",
    financialRates: "நிதி சதவீத விகிதங்கள்",
    lapsAlarm: "சுற்றுகள் & அலார ஒலி",
    precisionTrig: "துல்லிய முக்கோணவியல் இயந்திரம்",
    clientSafe: "பாதுகாப்பான உள்ளூர் கணினி சூழல்",
    quickChange: "% சதவீத மாற்றம்",
    theme: "தீம்",
    improFraction: "கலப்பு பின்னம்",
    rawRatio: "மூல விகிதம் பின்னங்கள்",
    reducedAnswer: "சுருக்கப்பட்ட எளிய விடை"
  },
  tr: {
    basic: "Basit Mod",
    scientific: "Bilimsel",
    fraction: "Kesirli",
    percentage: "Yüzde",
    timer: "Zamanlayıcı / Saat",
    history: "Geçmiş",
    clearHistory: "Geçmişi Temizle",
    emptyHistory: "Henüz geçmiş yok",
    clearInputs: "Girişleri Temizle",
    sound: "Tuş Sesi",
    fullscreen: "Tam Ekran",
    about: "OmniCalc Hakkında",
    result: "Sonuç",
    stepByStep: "Adım Adım",
    keyboard: "Klavye Kılavuzu",
    language: "Dil",
    simpleLayout: "Kolay Tasarım",
    trigFunctions: "Trigonometri & Fonksiyonlar",
    stepSolver: "Kesirli Adım Adım Çözücü",
    financialRates: "Finansal Yüzdeler",
    lapsAlarm: "Turlar & Alarm Sesi",
    precisionTrig: "Hassas Trigonometri Motoru",
    clientSafe: "Güvenli Tarayıcı Altyapısı",
    quickChange: "% Fark Değişimi",
    theme: "Tema",
    improFraction: "Tam Sayılı Kesir",
    rawRatio: "ORAN DETAYI",
    reducedAnswer: "SADELEŞMİŞ CEVAP"
  },
  vi: {
    basic: "Cơ bản",
    scientific: "Khoa học",
    fraction: "Phân số",
    percentage: "Phần trăm",
    timer: "Hẹn giờ / Đồng hồ",
    history: "Lịch sử",
    clearHistory: "Xóa Lịch sử",
    emptyHistory: "Chưa có phép tính nào",
    clearInputs: "Xóa dữ liệu nhập",
    sound: "Âm thanh",
    fullscreen: "Toàn màn hình",
    about: "Giới thiệu OmniCalc",
    result: "Kết quả",
    stepByStep: "Các bước giải",
    keyboard: "Hướng dẫn bàn phím",
    language: "Ngôn ngữ",
    simpleLayout: "Giao diện đơn giản",
    trigFunctions: "Lượng giác & Hàm số",
    stepSolver: "Giải phân số từng bước",
    financialRates: "Tỷ lệ tài chính",
    lapsAlarm: "Vòng chạy & Chuông báo",
    precisionTrig: "Động cơ Lượng giác độ chính xác cao",
    clientSafe: "Môi trường an toàn phía máy khách",
    quickChange: "Tỷ lệ thay đổi từ/đến",
    theme: "Giao diện",
    improFraction: "Hỗn số",
    rawRatio: "TỶ LỆ CHƯA RÚT GỌN",
    reducedAnswer: "ĐÁP ÁN RÚT GỌN"
  },
  fa: {
    basic: "حالت ساده",
    scientific: "علمی مهندسی",
    fraction: "کسرها",
    percentage: "درصدگیری",
    timer: "تایمرها و ساعت",
    history: "تاریخچه محاسبات",
    clearHistory: "پاک کردن تاریخچه",
    emptyHistory: "هیچ محاسبه‌ای ثبت نشده",
    clearInputs: "پاک کردن ورودی‌ها",
    sound: "صدای لمس دکمه‌ها",
    fullscreen: "تمام صفحه",
    about: "درباره OmniCalc",
    result: "نتیجه نهایی",
    stepByStep: "گام به گام آموزشی",
    keyboard: "راهنمای دکمه‌های کیبورد",
    language: "زبان اپلیکیشن",
    simpleLayout: "ظاهر ساده",
    trigFunctions: "توابع مثلثاتی ریاضی",
    stepSolver: "حل گام به گام کسر",
    financialRates: "درصدهای مالی",
    lapsAlarm: "ثبت دور و صداهای آلارم",
    precisionTrig: "موتور مثلثاتی فوق دقیق",
    clientSafe: "محیط امن و بدون نیاز به سرور",
    quickChange: "درصد افزایش یا کاهش",
    theme: "تم رنگی",
    improFraction: "عدد مخلوط",
    rawRatio: "نسبت اولیه کسر",
    reducedAnswer: "کسر ساده شده نهایی"
  },
  pl: {
    basic: "Tryb Podstawowy",
    scientific: "Naukowy",
    fraction: "Ułamki",
    percentage: "Procenty",
    timer: "Stoper / Minutnik",
    history: "Historia",
    clearHistory: "Wyczyść Historię",
    emptyHistory: "Brak zapisanych obliczeń",
    clearInputs: "Wyczyść Dane",
    sound: "Dźwięk Kliknięć",
    fullscreen: "Pełny Ekran",
    about: "O OmniCalc",
    result: "Wynik",
    stepByStep: "Krok po Kroku",
    keyboard: "Instrukcja Klawiszy",
    language: "Język",
    simpleLayout: "Klasyczny Wygląd",
    trigFunctions: "Trigonometria i Funkcje",
    stepSolver: "Rozwiązywanie Ułamków",
    financialRates: "Wskaźniki Procentowe",
    lapsAlarm: "Okrążenia i Alarmy",
    precisionTrig: "Precyzyjny Silnik Trygonometryczny",
    clientSafe: "Bezpieczne Środowisko Lokalne",
    quickChange: "Zmiana procentowa od/do",
    theme: "Motyw",
    improFraction: "Liczba Mieszana",
    rawRatio: "UŁAMEK NIEUPROSZCZONY",
    reducedAnswer: "CZYSTA POSTAĆ UŁAMKA"
  },
  uk: {
    basic: "Простий режим",
    scientific: "Науковий",
    fraction: "Дроби",
    percentage: "Відсотки",
    timer: "Таймери / Годинник",
    history: "Історія",
    clearHistory: "Очистити історію",
    emptyHistory: "Немає записів",
    clearInputs: "Очистити ввод",
    sound: "Звук клавіш",
    fullscreen: "Повний екран",
    about: "Про OmniCalc",
    result: "Результат",
    stepByStep: "Покроково",
    keyboard: "Клавіатура",
    language: "Мова",
    simpleLayout: "Звичайний вигляд",
    trigFunctions: "Тригонометрія",
    stepSolver: "Рішення дробів покроково",
    financialRates: "Фінансові розрахунки",
    lapsAlarm: "Кола та будильник",
    precisionTrig: "Точний тригонометричний рушій",
    clientSafe: "Локальне безпечне оточення",
    quickChange: "% зміна від/до",
    theme: "Тема",
    improFraction: "Мішане число",
    rawRatio: "НЕОБРОБЛЕНИЙ ДРІБ",
    reducedAnswer: "СКОРОЧЕНА ВІДПОВІДЬ"
  },
  ro: {
    basic: "Mod Simplu",
    scientific: "Științific",
    fraction: "Fracții",
    percentage: "Procent",
    timer: "Cronometru / Ceas",
    history: "Istoric",
    clearHistory: "Șterge Istoric",
    emptyHistory: "Nu există calcule",
    clearInputs: "Șterge Datele",
    sound: "Sunete Taste",
    fullscreen: "Ecran Complet",
    about: "Despre OmniCalc",
    result: "Rezultat",
    stepByStep: "Pas cu Pas",
    keyboard: "Ghid Tastatură",
    language: "Limbă",
    simpleLayout: "Design Clasic",
    trigFunctions: "Trigonometrie și Funcții",
    stepSolver: "Rezolvare Fracții Pas cu Pas",
    financialRates: "Procente și Rate",
    lapsAlarm: "Ture și Semnal Alarmă",
    precisionTrig: "Motor Trigonometric de Precizie",
    clientSafe: "Mediu Sigur în Browser Client",
    quickChange: "Variație valoare de la/la",
    theme: "Temă",
    improFraction: "Număr Mixt",
    rawRatio: "FRACȚIE INITIALĂ",
    reducedAnswer: "REZULTAT SIMPLIFICAT"
  },
  el: {
    basic: "Απλή Λειτουργία",
    scientific: "Επιστημονικό",
    fraction: "Κλάσματα",
    percentage: "Ποσοστό",
    timer: "Χρονόμετρα / Ρολόι",
    history: "Ιστορικό",
    clearHistory: "Καθαρισμός Ιστορικού",
    emptyHistory: "Δεν υπάρχουν ακόμη υπολογισμοί",
    clearInputs: "Καθαρισμός Εισαγωγών",
    sound: "Ήχοι Πλήκτρων",
    fullscreen: "Πλήρης Οθόνη",
    about: "Σχετικά με το OmniCalc",
    result: "Αποτέλεσμα",
    stepByStep: "Βήμα προς Βήμα",
    keyboard: "Οδηγός Πληκτρολογίου",
    language: "Γλώσσα",
    simpleLayout: "Απλή Διάταξη",
    trigFunctions: "Τριγωνομετρία & الدوال",
    stepSolver: "Βήμα-Βήμα Επίλυση Κλασμάτων",
    financialRates: "Χρηματοοικονομικά Ποσοστά",
    lapsAlarm: "Γύροι & Ήχος Ξυπνητηριού",
    precisionTrig: "Μηχανή Τριγωνομετρίας Ακριβείας",
    clientSafe: "Ασφαλές Περιβάλλον Πελάτη",
    quickChange: "% Διαφορά από/σε",
    theme: "Θέμα",
    improFraction: "Μεικτός Αριθμός",
    rawRatio: "ΑΡΧΙΚΟΣ ΛΟΓΟΣ ΚΛΑΣΜΑΤΟΣ",
    reducedAnswer: "ΑΠΛΟΠΟΙΗΜΕΝΗ ΑΠΑΝΤΗΣΗ"
  },
  cs: {
    basic: "Základní režim",
    scientific: "Vědecká",
    fraction: "Zlomky",
    percentage: "Procenta",
    timer: "Stopky / Odpočet",
    history: "Historie",
    clearHistory: "Smazat historii",
    emptyHistory: "Zatím žádné výpočty",
    clearInputs: "Smazat hodnoty",
    sound: "Zvuky kláves",
    fullscreen: "Celá obrazovka",
    about: "O aplikaci OmniCalc",
    result: "Výsledek",
    stepByStep: "Krok za krokem",
    keyboard: "Klávesové zkratky",
    language: "Jazyk",
    simpleLayout: "Rychlé rozvržení",
    trigFunctions: "Trigonometrie",
    stepSolver: "Krokový řešič zlomků",
    financialRates: "Procentuální změny",
    lapsAlarm: "Kola & Budík",
    precisionTrig: "Přesný trigonometrický engine",
    clientSafe: "Zabezpečené klientské prostředí",
    quickChange: "Změna z hodnoty / na",
    theme: "Vzhled",
    improFraction: "Smíšené číslo",
    rawRatio: "NEZKRÁCENÝ PHOMĚR",
    reducedAnswer: "ZKRÁCENÝ ZLOMEK"
  },
  sv: {
    basic: "Enkelt Läge",
    scientific: "Vetenskaplig",
    fraction: "Bråktal",
    percentage: "Procent",
    timer: "Tidtagare / Klocka",
    history: "Historik",
    clearHistory: "Rensa Historik",
    emptyHistory: "Inga sparade beräkningar",
    clearInputs: "Rensa fält",
    sound: "Knappljud",
    fullscreen: "Helskärm",
    about: "Om OmniCalc",
    result: "Resultat",
    stepByStep: "Steg-för-steg",
    keyboard: "Tangentbordsguide",
    language: "Språk",
    simpleLayout: "Standardvy",
    trigFunctions: "Trigonometri",
    stepSolver: "Stegvis lösning av bråk",
    financialRates: "Procentuella förändringar",
    lapsAlarm: "Varvtider & Larmton",
    precisionTrig: "Trigonometri-motor med hög precision",
    clientSafe: "Säker offline-miljö på klientsidan",
    quickChange: "Förändring från/till",
    theme: "Tema",
    improFraction: "Blandat Tal",
    rawRatio: "URSPRUNGLIGT BRÅKTAL",
    reducedAnswer: "FÖRENKLAT SVAR"
  },
  no: {
    basic: "Enkel Modus",
    scientific: "Vitenskapelig",
    fraction: "Brøk",
    percentage: "Prosent",
    timer: "Stoppeklokke / Alarm",
    history: "Historikk",
    clearHistory: "Tøm Historikk",
    emptyHistory: "Ingen beregninger ennå",
    clearInputs: "Rensa felter",
    sound: "Tastelyder",
    fullscreen: "Fullskjerm",
    about: "Om OmniCalc",
    result: "Resultat",
    stepByStep: "Steg-for-steg",
    keyboard: "Tastaturguide",
    language: "Språk",
    simpleLayout: "Enkelt utseende",
    trigFunctions: "Trigonometri",
    stepSolver: "Stegvis Brøkløser",
    financialRates: "Prosentvise endringer",
    lapsAlarm: "Runder & Alarmlyd",
    precisionTrig: "Nøyaktig trigonometrimaskin",
    clientSafe: "Sikkert brukergrensesnitt",
    quickChange: "Endring fra/til",
    theme: "Tema",
    improFraction: "Blandet Tall",
    rawRatio: "UFORENKLET FORHOLD",
    reducedAnswer: "FORENKLET SVAR"
  },
  da: {
    basic: "Enkel Tilstand",
    scientific: "Videnskabelig",
    fraction: "Brøkdele",
    percentage: "Procent",
    timer: "Stopur / Minutur",
    history: "Historik",
    clearHistory: "Ryd historik",
    emptyHistory: "Ingen beregninger endnu",
    clearInputs: "Ryd felter",
    sound: "Knaptoner",
    fullscreen: "Fuld skærm",
    about: "Om OmniCalc",
    result: "Resultat",
    stepByStep: "Trin-for-trin",
    keyboard: "Tastaturguide",
    language: "Sprog",
    simpleLayout: "Enkel struktur",
    trigFunctions: "Trigonometri",
    stepSolver: "Trinvis Brøkløser",
    financialRates: "Surcharge & Marginer",
    lapsAlarm: "Omgange & Alarmlyd",
    precisionTrig: "Højpræcis trigonometri-motor",
    clientSafe: "Sikkert klientside-miljø",
    quickChange: "% ændring fra/til",
    theme: "Tema",
    improFraction: "Blandet Tal",
    rawRatio: "UFORENKLET BRØK",
    reducedAnswer: "REDUCERET CEVAP"
  },
  fi: {
    basic: "Perustila",
    scientific: "Tieteellinen",
    fraction: "Murtoluvut",
    percentage: "Prosentti",
    timer: "Sekuntikello / Ajastin",
    history: "Historia",
    clearHistory: "Tyhjennä historia",
    emptyHistory: "Ei tallennettuja laskuja",
    clearInputs: "Tyhjennä kentät",
    sound: "Näppäinäänet",
    fullscreen: "Koko näyttö",
    about: "Tietoja sovelluksesta",
    result: "Tulokset",
    stepByStep: "Vaiheittain",
    keyboard: "Pikanäppäimet",
    language: "Kieli",
    simpleLayout: "Yksinkertainen rakenne",
    trigFunctions: "Trigonometria",
    stepSolver: "Murtolukujen vaiheittainen ratkaisin",
    financialRates: "Prosentuaaliset muutokset",
    lapsAlarm: "Kierrosajat & Hälytys",
    precisionTrig: "Tarkka trigonometriamoottori",
    clientSafe: "Turvallinen klientside-pohja",
    quickChange: "Muutos arvosta/arvoon",
    theme: "Teema",
    improFraction: "Sakaluku",
    rawRatio: "LASKEMATON SUHDE",
    reducedAnswer: "SUPISTETTU VASTAUS"
  },
  he: {
    basic: "מצב בסיסי",
    scientific: "מחשבון מדעי",
    fraction: "شברים (שברים)",
    percentage: "אחוזים",
    timer: "טיימר / שעון",
    history: "היסטוריה",
    clearHistory: "נקה היסטוריה",
    emptyHistory: "אין פריטים בהיסטוריה",
    clearInputs: "נקה שדות",
    sound: "צלילי כפתורים",
    fullscreen: "מסך מלא",
    about: "אודות OmniCalc",
    result: "תוצאה",
    stepByStep: "צעד אחר צעד",
    keyboard: "מדריך מקלדת",
    language: "שפה",
    simpleLayout: "מבנה פשוט",
    trigFunctions: "טריגונומטריה ופונקציות",
    stepSolver: "פתרון שברים מפורט",
    financialRates: "חישובי אחוזים ומיסים",
    lapsAlarm: "הקפות וצליל התראה",
    precisionTrig: "מנוע טריגונומטריה מדויק",
    clientSafe: "סביבה בטוחה ללא שרתים",
    quickChange: "% שינוי מערך / לערך",
    theme: "ערכת נושא",
    improFraction: "מספר מעורב",
    rawRatio: "יחס גולמי",
    reducedAnswer: "שבר מצומצם"
  },
  id: {
    basic: "Mode Dasar",
    scientific: "Ilmiah (Sains)",
    fraction: "Pecahan",
    percentage: "Persentase",
    timer: "Pewaktu / Jam",
    history: "Riwayat",
    clearHistory: "Hapus Riwayat",
    emptyHistory: "Belum ada perhitungan",
    clearInputs: "Kosongkan Input",
    sound: "Nada Sentuh",
    fullscreen: "Layar Penuh",
    about: "Tentang OmniCalc",
    result: "Hasil",
    stepByStep: "Langkah demi Langkah",
    keyboard: "Panduan Keyboard",
    language: "Bahasa",
    simpleLayout: "Tampilan Sederhana",
    trigFunctions: "Trigonometri & Fungsi",
    stepSolver: "Solusi Pecahan Detil",
    financialRates: "Persentase Finansial",
    lapsAlarm: "Lap & Alarme Bunyi",
    precisionTrig: "Mesin Trigonometri Presisi Tinggi",
    clientSafe: "Lingkungan Aman Sisi-Klien",
    quickChange: "Perubahan Dari/Ke",
    theme: "Tema",
    improFraction: "Pecahan Campur",
    rawRatio: "PECAHAN TOTAL",
    reducedAnswer: "JAWABAN SEDERHANA"
  },
  ms: {
    basic: "Mod Asas",
    scientific: "Saintifik",
    fraction: "Pecahan",
    percentage: "Peratusan",
    timer: "Pemasa / Jam",
    history: "Sejarah",
    clearHistory: "Padam Sejarah",
    emptyHistory: "Tiada sejarah pengiraan",
    clearInputs: "Kosongkan Input",
    sound: "Bunyi Sentuhan",
    fullscreen: "Skrin Penuh",
    about: "Mengenai OmniCalc",
    result: "Keputusan",
    stepByStep: "Langkah Demi Langkah",
    keyboard: "Panduan Papan Kekunci",
    language: "Bahasa",
    simpleLayout: "Reka Letak Mudah",
    trigFunctions: "Trigonometri & Fungsi",
    stepSolver: "Penyelesaian Pecahan Terperinci",
    financialRates: "Surcharge & Diskaun",
    lapsAlarm: "Laps & Alarm Chime",
    precisionTrig: "Enjin Trigonometri Tepat",
    clientSafe: "Persekitaran Selamat Mesra Pelayar",
    quickChange: "Kadar perubahan dari/ke",
    theme: "Tema",
    improFraction: "Nombor Bercampur",
    rawRatio: "PECAHAN ASAL",
    reducedAnswer: "JAWABAN TERENDAH"
  },
  th: {
    basic: "โหมดพื้นฐาน",
    scientific: "เครื่องคิดเลขวิทยาศาสตร์",
    fraction: "เศษส่วน",
    percentage: "เปอร์เซ็นต์",
    timer: "จับเวลา / นาฬิกา",
    history: "ประวัติการใช้งาน",
    clearHistory: "ล้างประวัติ",
    emptyHistory: "ยังไม่มีประวัติการคำนวณ",
    clearInputs: "ล้างตัวเลขเข้า",
    sound: "เสียงกดปุ่ม",
    fullscreen: "เต็มหน้าจอ",
    about: "เกี่ยวกับ OmniCalc",
    result: "ผลลัพธ์",
    stepByStep: "แสดงวิธีทำทีละขั้นตอน",
    keyboard: "คำแนะนำคีย์บอร์ด",
    language: "ภาษา",
    simpleLayout: "หน้าต่างใช้งานทั่วไป",
    trigFunctions: "ตรีโกณมิติและฟังค์ชั่น",
    stepSolver: "แก้โจทย์เศษส่วนทีละสเต็ป",
    financialRates: "เปอร์เซ็นต์ทางการเงิน",
    lapsAlarm: "รอบจับเวลาพร้อมเสียงเตือน",
    precisionTrig: "เอนจิ้นตรีโกณมิติความแม่นยำสูง",
    clientSafe: "ระบบความปลอดภัยฝั่งไคลเอนต์",
    quickChange: "คำนวณการเปลี่ยนแปลง จาก/ถึง",
    theme: "ธีม",
    improFraction: "เศษส่วนคละ",
    rawRatio: "เศษส่วนดิบ",
    reducedAnswer: "เศษส่วนอย่างต่ำ"
  },
  tl: {
    basic: "Karaniwang Mode",
    scientific: "Siyentipiko",
    fraction: "Praksyon",
    percentage: "Porsyento",
    timer: "Orasan / Timer",
    history: "Kasaysayan",
    clearHistory: "I-clear ang Kasaysayan",
    emptyHistory: "Wala pang mga kalkulasyon",
    clearInputs: "I-clear ang Input",
    sound: "Tunog ng Pindutan",
    fullscreen: "Full Screen",
    about: "Tungkol sa OmniCalc",
    result: "Resulta",
    stepByStep: "Hakbang-hakbang",
    keyboard: "Gabay sa Keyboard",
    language: "Wika",
    simpleLayout: "Simpleng Layout",
    trigFunctions: "Trigonometry & Functions",
    stepSolver: "Step Solver ng Praksyon",
    financialRates: "Porsyento ng Pananalapi",
    lapsAlarm: "Mga Lap at Tunog ng Alarm",
    precisionTrig: "High Precision Trigonometry Engine",
    clientSafe: "Safe na Klientside Environment",
    quickChange: "Porsyentong pagbabago mula/tungo",
    theme: "Tema",
    improFraction: "Mixed Number",
    rawRatio: "PROPORSIYONG RAW",
    reducedAnswer: "PINASIMPLENG SAGOT"
  },
  hu: {
    basic: "Alap Mód",
    scientific: "Tudományos",
    fraction: "Törtek",
    percentage: "Százalék",
    timer: "Stopper / Időzítő",
    history: "Előzmények",
    clearHistory: "Előzmények Törlése",
    emptyHistory: "Még nincsenek számítások",
    clearInputs: "Bevitelek Törlése",
    sound: "Gombhangok",
    fullscreen: "Teljes Képernyő",
    about: "Az OmniCalc-ról",
    result: "Eredmény",
    stepByStep: "Lépésről Lépésre",
    keyboard: "Billentyűzet Útmutató",
    language: "Nyelv",
    simpleLayout: "Egyszerű Elrendezés",
    trigFunctions: "Trigonometria és Függvények",
    stepSolver: "Törtek Részletes Megoldása",
    financialRates: "Pénzügyi Százalékok",
    lapsAlarm: "Köridők és Ébresztő",
    precisionTrig: "Nagy Pontosságú Trigonometriai Motor",
    clientSafe: "Biztonságos Kliensoldali Környezet",
    quickChange: "Százalékos eltérés tól/ig",
    theme: "Téma",
    improFraction: "Vegyes Tört",
    rawRatio: "EREDETI HÁNYADOS",
    reducedAnswer: "EGYSZERŰSÍTETT MEGOLDÁS"
  },
  hr: {
    basic: "Osnovni način",
    scientific: "Znanstveni",
    fraction: "Razlomci",
    percentage: "Postotak",
    timer: "Štoperica / Timer",
    history: "Povijest",
    clearHistory: "Očisti Povijest",
    emptyHistory: "Nema spremljenih izračuna",
    clearInputs: "Očisti Polja",
    sound: "Zvuk Tipki",
    fullscreen: "Cijeli Zaslon",
    about: "O OmniCalcu",
    result: "Rezultat",
    stepByStep: "Korak po Korak",
    keyboard: "Prečaci Tipkovnice",
    language: "Jezik",
    simpleLayout: "Jednostavan Izgled",
    trigFunctions: "Trigonometrija i Funkcije",
    stepSolver: "Detaljno Rješavanje Razlomaka",
    financialRates: "Financijske Stope",
    lapsAlarm: "Krugovi i Alarmi",
    precisionTrig: "Precizni Trigonometrijski Engine",
    clientSafe: "Lokalno Sigurno Okruženje",
    quickChange: "Postotna promjena od/do",
    theme: "Tema",
    improFraction: "Mješoviti Broj",
    rawRatio: "NERESVEDENI OMJER",
    reducedAnswer: "REDUCIRANI ODGOVOR"
  },
  sk: {
    basic: "Základný režim",
    scientific: "Vedecká",
    fraction: "Zlomky",
    percentage: "Percentá",
    timer: "Stopky / Odpočet",
    history: "História",
    clearHistory: "Vymazať históriu",
    emptyHistory: "Zatiaľ žiadne výpočty",
    clearInputs: "Vymazať vstupy",
    sound: "Zvuky kláves",
    fullscreen: "Celá obrazovka",
    about: "O aplikácii OmniCalc",
    result: "Výsledok",
    stepByStep: "Krok za krokom",
    keyboard: "Klávesové skratky",
    language: "Jazyk",
    simpleLayout: "Klasické rozvrhnutie",
    trigFunctions: "Trigonometria a funkcie",
    stepSolver: "Krokové riešenie zlomkov",
    financialRates: "Finančné úrovne",
    lapsAlarm: "Kola & Alarm",
    precisionTrig: "Presný trigonometrický stroj",
    clientSafe: "Zabezpečené klientske prostredie",
    quickChange: "Zmena hodnoty od/do",
    theme: "Vzhľad",
    improFraction: "Zmiešané číslo",
    rawRatio: "NEZJEDNODUŠENÝ POMER",
    reducedAnswer: "ZJEDNODUŠENÝ VÝSLEDOK"
  }
};
